version: "3.5"

services:
  client:
    build: ./client
    container_name: client
    ports:
      - 8080:80

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo