global:
    checkNewVersion: true
    sendAnonymousUsage: false
  
  serversTransport:
    insecureSkipVerify: true
  
  log:
    level: INFO
  
  accessLog:
    filePath: "/access.log"
  
  api:
    dashboard: true
    insecure: true
  
  entryPoints:
    http:
      address: :80
    https:
      address: :443
  
  providers:
    docker:
      endpoint: unix:///var/run/docker.sock
      exposedByDefault: false
      watch: true
    file:
      filename: config.yml
      watch: true
  
  certificatesResolvers:
    http:
      acme:
        email: allankimmerjensen@gmail.com
        storage: acme.json
        dnsChallenge:
          provider: cloudflare
  